general:
  output_dir: /home/david/code/moco/results/imagenet
  log_to_wandb: True
  checkpoint_freq: 10
data:
  dataset: imagenet
  dataset_root: /mnt/data/home/david/data/imagenet/data
optim:
  lr: 0.07
  weight_decay: 1.0e-10
  workers: 8
  batch_size: 16
  epochs: 500
  device: cuda
